---
title: "day2"
author: "olivier"
date: "12/2/2021"
output: html_document
---

# Day 2 at #adventofcode

## Part1

The riddle to solve is [here](https://adventofcode.com/2021/day/2). 


### Loading data 

```{r}
direction <- read.csv("data/day2", header = F, sep = " ")
names(direction) <- c("arrow", "unit")
```

### Moving the sub

I will try first to implement moving forward then I will add the two other options.

```{r}
horiz_pos <- sum(direction$unit[direction$arrow == "forward"])

horiz_pos
```


```{r}
depth <- sum(direction$unit[direction$arrow == "down"]) - sum(direction$unit[direction$arrow == "up"])

depth
```

```{r}
horiz_pos * depth
```

## Part 2

[Here](https://adventofcode.com/2021/day/2#part2)

I will try to keep track of aim and depth. Horizontal position doesn't change.

```{r}

aim <- 0
depth <- 0

for (i in 1:length(direction$arrow))
    {
    ifelse(direction$arrow[i] == "forward",
           {aim <- aim + 0;
           depth <- depth + (aim * direction$unit[i])},
           ifelse(direction$arrow[i] == "up",
                  aim <- aim - direction$unit[i],
                  aim <- aim + direction$unit[i]
           )) 
    #print(aim)
    #print(depth)
    }

```

```{r}
depth * horiz_pos
```

